# Generated by Django 4.1.5 on 2023-01-17 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 22, 30, 50, 580661)),
        ),
    ]
