# Generated by Django 4.1.5 on 2023-01-20 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 8, 22, 38, 194376, tzinfo=datetime.timezone.utc)),
        ),
    ]
