# Generated by Django 4.1.5 on 2023-01-20 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0002_alter_announcement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 9, 52, 40, 428540, tzinfo=datetime.timezone.utc)),
        ),
    ]
