# Generated by Django 4.1.5 on 2023-01-17 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0002_announcement_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 17, 2, 18, 706219, tzinfo=datetime.timezone.utc)),
        ),
    ]
