# Generated by Django 4.1.5 on 2023-01-18 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drive', '0001_initial'),
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('Cluster_id', models.IntegerField(primary_key=True, serialize=False)),
                ('starting', models.FloatField(default=0)),
                ('ending', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('board', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('college_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(max_length=254)),
                ('gender', models.CharField(default='', max_length=100)),
                ('pnumber', models.BigIntegerField()),
                ('pincode', models.BigIntegerField()),
                ('dob', models.DateField(null=True)),
                ('batch_year', models.IntegerField()),
                ('sitting_for', models.CharField(choices=[('intern', 'Internship'), ('placement', 'Placement')], default='placement', max_length=100)),
                ('resume', models.CharField(default='', max_length=200)),
                ('undertaking', models.BooleanField()),
                ('cgpi', models.FloatField(default=0)),
                ('gate_score', models.IntegerField(null=True)),
                ('cat_score', models.FloatField(null=True)),
                ('class_10_year', models.IntegerField()),
                ('class_10_perc', models.FloatField()),
                ('class_12_year', models.IntegerField()),
                ('class_12_perc', models.FloatField()),
                ('active_backlog', models.SmallIntegerField()),
                ('total_backlog', models.SmallIntegerField()),
                ('linkedin', models.CharField(default='', max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.specialization')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.city')),
                ('roll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.country')),
            ],
        ),
        migrations.CreateModel(
            name='Recruited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype', models.CharField(choices=[('intern', 'Internship'), ('placement', 'Placement')], max_length=20)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.drive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterChosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_1', to='student.cluster')),
                ('cluster_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_2', to='student.cluster')),
                ('cluster_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_3', to='student.cluster')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.state'),
        ),
    ]
