# Generated by Django 4.1.5 on 2023-01-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Recruited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtype', models.CharField(choices=[('intern', 'Internship'), ('placement', 'Placement')], max_length=20)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.drive')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
    ]
